### ISSUE TITLE
Is it possible to do a conda install version

### ISSUE THREAD

**Issue by kelejichi6463** [kevinzakka/mink#23]
Hello author, I get an error when installing with PIP that there is no suitable mink version, so I would like to ask you if it is possible to make an installation version of conda. Thank you very much

**Comment by jonzamora** [comment]
Yeah, you can try this `environment.yaml`

```YAML
name: mujoco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mink[examples]
      - 
```

Then, just run `conda` or [`mamba`](https://mamba.readthedocs.io/en/latest/) like so: `mamba env create -f environment.yaml` and `mamba activate mujoco`. You should be able to run `mink` and its related scripts after this.
